name: perfect_three
description: 3일 반복 성공 구조를 통해 습관을 형성하는 앱
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # [상태 관리] 앱의 데이터 흐름을 관리하는 최고의 라이브러리
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # [화면 이동] 화면 간의 이동(라우팅)을 쉽고 직관적으로 처리
  go_router: ^17.0.0

  # [로컬 데이터베이스] 데이터를 폰에 빠르고 안전하게 저장 (Hive)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # [광고] 수익화를 위한 구글 애드몹
  google_mobile_ads: ^6.0.0

  # [유틸리티] 날짜 포맷, 다국어 지원 등을 도움
  intl: ^0.20.2
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1

  # [알림] 로컬 알림 처리
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1

  # [로깅] 개발 중 로그를 예쁘고 보기 쉽게 출력
  logger: ^2.6.2

  # [경로] 파일 시스템 경로를 쉽게 찾게 해줌
  path_provider: ^2.1.5
  # [앱 정보] 앱 버전, 패키지명 등 정보 가져오기
  package_info_plus: ^8.1.1
  # [모델] 고유 id 생성
  uuid:
  # [폰트]
  google_fonts: ^6.3.2
  # [이모티콘]
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # [코드 생성] 반복적인 코드를 자동으로 작성해주는 도구들
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.0
  hive_generator: ^2.0.1
  analyzer: ^6.4.1

  # [린트] 코드를 깔끔하고 규격에 맞게 작성하도록 도와줌
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # [에셋] 이미지와 다국어 파일 등을 등록합니다.
  assets:
    - assets/json/
