name: perfect_three
description: 3일 반복 성공 구조를 통해 습관을 형성하는 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # [상태 관리] 앱의 데이터 흐름을 관리하는 최고의 라이브러리
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  

  # [화면 이동] 화면 간의 이동(라우팅)을 쉽고 직관적으로 처리
  go_router: 

  # [로컬 데이터베이스] 데이터를 폰에 빠르고 안전하게 저장 (Hive)
  hive: 
  hive_flutter: 
  

  # [광고] 수익화를 위한 구글 애드몹
  google_mobile_ads: ^6.0.0

  # [유틸리티] 날짜 포맷, 다국어 지원 등을 도움
  intl: 

  # [로깅] 개발 중 로그를 예쁘고 보기 쉽게 출력
  logger: 

  # [경로] 파일 시스템 경로를 쉽게 찾게 해줌
  path_provider: 
  # [모델] 고유 id 생성
  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # [코드 생성] 반복적인 코드를 자동으로 작성해주는 도구들
  build_runner: ^2.4.13 
  riverpod_generator: ^2.4.0
  hive_generator: 
  analyzer: 
  
  
  # [린트] 코드를 깔끔하고 규격에 맞게 작성하도록 도와줌
  flutter_lints: 

flutter:
  uses-material-design: true
  
  # [에셋] 이미지와 다국어 파일 등을 등록합니다.
  assets:
    - assets/json/